const constants = {
    SHOW_AUTH: 'FORM_AUTHORIZATION',
    SHOW_CHARACTER_SELECTOR: 'FORM_CHARACTER',
    HIDE_CHARACTER_SELECTOR: 'HIDE_FORM_CHARACTER',
    ADD_FORM: 'ADD_FORM',
    SET_FORM: 'SET_FORM',
    SHOW_MESSAGE_BOX: 'SHOW_MESSAGE_BOX',
    SHOW_EDIT_BOX: 'SHOW_EDIT_BOX',
    CLOSE_DIALOG: 'CLOSE_DIALOG',
    SET_IS_LOADING: 'SET_IS_LOADING',
};

export default constants;